- name: Install MariaDB
  apt:
    name: mariadb-server
    state: present

- name: Configure MariaDB
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
  notify: restart mariadb

- name: Install python3-pip
  apt:
    name: python3-pip
    state: present

- name: Install libmysqlclient-dev
  apt:
    name: libmysqlclient-dev
    state: present

- name: Install the Python MySQLdb module
  apt:
    name: python3-mysqldb
    state: present

- name: Create MariaDB users
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    config_file: /etc/mysql/debian.cnf
    priv: "{{ item.privileges }}"
    append_privs: "{{ item.append_privileges | default('yes') }}"
  with_items: "{{ mariadb_users }}"

- name: Create MariaDB databases
  mysql_db:
    name: "{{ item }}"
    state: present
    config_file: /etc/mysql/debian.cnf
  with_items: "{{ mariadb_bases }}"
